  on:
    schedule:
      - cron: "5 0 * * TUE-SAT"

  jobs:
    build-and-publish-snapshot:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 22
          uses: actions/setup-java@v4
          with:
            java-version: '22'
            distribution: 'temurin'
            #          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
            #          settings-path: ${{ github.workspace }} # location for the settings.xml file
        - name: Define library version env var at run-time - SNAPSHOT
          run: |
            "export ORG_GRADLE_PROJECT_LIBRARY_VERSION=`git tag | tail -1`-SNAPSHOT" >> $GITHUB_ENV
            source $GITHUB_ENV

        # This step is needed because Gradle doesn't like to see GPG keys from env vars (for reasons unbeknownst to me)
        - name: Inject Gradle signing key from GHA secret
          run: |
            echo $GPG_SIGNING_KEY \
              | awk 'NR == 1 { print "SIGNING_KEY=" } 1' ORS='\\n' \
              >> gradle.properties

        - name: Publish snapshots to Maven Central
          run: |
            ./gradlew publishToSonatype
